### PR TITLE
Created Footprint library Housings_LCC

### PR DESCRIPTION
**Pull request by yo3iti**
Created Footprint library Housings_LCC to accomodate (for now) LCC-20_9x9mm for one of the RF Power Sensors in analog_devices pull request.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

just had a chance to take a first look at this PR. There are a few things that should be changed:
1. There should be some kind of pin1- or orientation marker on the silkscreen layer that is visible AFTER assembly
2. There ahouls also be a pin1-marker on F.Fab
3. Silkscreen should have a linewidth of 0.12mm
4. Courtyard should have an offset of 0.25mm and be on a grid of 0.01mm (i.e. round the coordinates to 0.01mm)
5. Set the properties correctly:
2017-02-25 14_15_39-footprint editor no active library

Note that our check-scripts also work for footprints: https://github.com/KiCad/kicad-library-utils/tree/master/pcb

Best,
JAN

**Comment by yo3iti** [comment]
Hi, Jan,

Thx. My comments, below, in red.

> Pe 25 feb. 2017, la 15:17, Jan W. Krieger <notifications@github.com> a scris:
> 
> Hi!
> 
> just had a chance to take a first look at this PR. There are a few things that should be changed:
> 
> There should be some kind of pin1- or orientation marker on the silkscreen layer that is visible AFTER assembly
Will change.
> There ahouls also be a pin1-marker on F.Fab
Will change.
> Silkscreen should have a linewidth of 0.12mm
Will change.
> Courtyard should have an offset of 0.25mm and be on a grid of 0.01mm (i.e. round the coordinates to 0.01mm)
If I set the offset to 0.25mm it lands directly on the solder mask.
> Set the properties correctly:
Here comes the fun; see how the same dialog looks on mac, v4.0.5 (below). Notice something funny ? Hint: SMD.
Ok, I will use my windows distribution, but PLEASE take this with dev team.
>  <https://cloud.githubusercontent.com/assets/11967523/23331370/097ddaa0-fb65-11e6-87a3-55063d0cd320.png>
> Note that our check-scripts also work for footprints: https://github.com/KiCad/kicad-library-utils/tree/master/pcb <https://github.com/KiCad/kicad-library-utils/tree/master/pcb>
> 
Regards,
Miron

**Comment by jkriege2** [comment]
About the dialog: I think that's not a Mac issues, but more an issue of whether you use a nightly, or a stable version ... I think those renames were introduced just later ... If not: Please post a bug-report to the devs!

**Comment by yo3iti** [comment]
Stable version 4.0.5. Will open a bug.

BR
M

**Comment by jkriege2** [comment]
Hi!

the F.Fab should mainly show the outline of the device. therefore I would suggest a pin1-mark like this:
2017-02-26 09_32_43-footprint editor no active library

Also: Please add a text `%R`to F.Fab so we also have the REFDES on that layer.

Best,
JAN

**Comment by jkriege2** [comment]
Looks good to me now. Only one thing missing: Please add a %R-label (a second REFDES) on the F.Fab layer!

Thanks,
JAN

**Comment by jkriege2** [comment]
Also: Please have a look at the errors reported by our shiny new ;-) check-scripts: https://travis-ci.org/KiCad/Housings_LCC.pretty/builds/209111904 and correct the bugs there ...

**Comment by jkriege2** [comment]
PPS: The courtyard should have an offset of 0.25mm from the outside of the pads!

**Comment by yo3iti** [comment]
Hi, Jan,

Thank you for your email.

I wrote in a previous email (a week ago) that I quit working on these. Sorry, I don't have much time to lose and all this github stuff and validation are quite tedious and error prone and I spent a lot of time solving issues that were not even captured in the KLC. Moreover, there seem to be no structured approach regarding who is doing what and when which makes all this more complicated than I thought. More project planning is needed here.

I will limit myself to UI translation and, maybe when I will have more time, I will dive deeper into these.
For now, I think contributing to KiCad for a non-programmer is a no-go because the process is too difficult to understand for a novice and support limited (verybody expects contributors to be knowledgeable in using these tools and scripts which, for most of us, is not the case).

We'll keep in touch. For now, please keep me in the lists. I will resume working on these when I will have more time from my job.

Regards,

Miron Iancu

**Comment by jkriege2** [comment]
Hi!

would be great if you (at some point) find time to come back to this ... For now I will keep it open.

About your general points, please keep a few things in mind:
1. We are all volunteers that donate their private time to this project + we are currently a rather small team of lib maintainers ... so as with many open-source projects that are not backed by a company, the ride might be a bit bumpy ;-) ... but then I think we try to do our best to help everybody ;-)
2. We are currently working (a bit behind the scenes) on a larger overhaul of the KLCs, including better explanations and images ... + scripts that check many of the rules. First results of this huge effort can be seen in the integration of automatic checks (TRAVIS), which you can see near the end of this thread: 
2017-03-08 22_03_01-created footprint library housings_lcc by yo3iti pull request 1 kicad_housi

Best,
JAN

**Comment by evanshultz** [comment]
@yo3iti Hi Miron, can you please advise if you'll have time to wrap up this PR soon? It seems the changes required now are rather small and I believe that KLC is much better these days. Please ask if you have more questions about how to resolve the remaining items. If you don't plan to complete this case, you may also close it to keep this repository tidy.

**Comment by evanshultz** [comment]
@yo3iti To tidy up the PRs I'll be closing this case unless I hear from you that you'll work on it again within 2 days. Since this footprint still exists in your fork of this repository, you can make the fixes and submit another PR if and when your time allows.

**Comment by evanshultz** [comment]
I do not see that this footprint exists in the library, but with the originator essentially abandoning the case it makes no sense to leave this PR open where it will get progressively more out of date. Already, I see all other LCC footprints use a chevon (looks something like an upside-down `^`) to mark pin 1. In addition, I don't see a datasheet above which makes it more difficult to fix as a third party. Closing.

**Pull request closed without merging**
