### PR TITLE
Added THT PLCC housings (script generated)

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Datasheet: http://www.mill-max.com/assets/pdfs/144.PDF

These have been script generated and are failing 9.2. I think it makes more sense to center the footprints rather than offset to Pin-1?

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi @SchrodingersGat !

Hmmm ... about centering: I would say we stick to the KLC-rule that we set up ... I think exceptions are acceptable (even desired and should be part of KLC) for parts, where we want to position a special part of a component (e.g. a switch button or potmeter axis), but for a generic IC housing/socket I don't see the reason ... Having it on pin1 makes sure that you can easily align other footprints around the PLCC-socket to the grid defined by the pins (using the snap-to grid of KiCAD).

So I would say: Move anchor to pin 1.

Best,
JAN

**Comment by jkriege2** [comment]
Otherwise the footprints look good!

Great work (on both PRs)!
JAN

**Comment by SchrodingersGat** [comment]
Done :)

**Comment by jkriege2** [comment]
Nice work!

JAN

**Pull request merged**
